version: 2
linters:
  enable:
    - testcomments
  settings:
    custom:
      testcomments:
        type: module
        description: lint that follows standards described in TestComments.
        settings:
          equality-comparison:
            reflect: true
          identify-function: true
          got-before-want: true
          table-driven-format:
            type: slice
            inlined: false
