version: 2
linters:
  enable:
    - testcomments
  settings:
    custom:
      testcomments:
        type: module
        description: lint that follows standards described in TestComments.
        settings:
          equality-comparison:
            reflect: false
          table-driven-format:
            type: slice
            inlined: false
